server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-course
    username: root
    password: 123456
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:com/lmk/hrm/mapper/*Mapper.xml
  type-aliases-package: com.lmk.hrm.domain,com.lmk.hrm.query