server:
  port: 9001
spring:
  application:
    name: hrm-sysmanage
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm-sysmanage
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:com/lmk/hrm/mapper/*Mapper.xml
  type-aliases-package: com.lmk.hrm.domain,com.lmk.hrm.query

